### ISSUE TITLE
Redirect more visible so we can manage Lists better.

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/BlueLL#1]
`a.mw-redirect { color: purple; opacity: 0.7; } /* or other better value */`

See also test : https://lingualibre.org/wiki/MediaWiki:Common.css

Hello @0x010C. May you confirm I have to submit changes to this file : 
* https://github.com/lingua-libre/BlueLL/blob/master/assets/stylesheets/main.css

**Comment by 0x010C** [comment]
The content.css would be a better choice:
https://github.com/lingua-libre/BlueLL/blob/master/assets/stylesheets/content.css

**Comment by hugolpz** [comment]
Implemented within Mediawiki:Common.css. So let's close this issue.

Now need to be considered for integration. See #5
