### ISSUE TITLE
 compatible with the upcoming 1.39 version of mediawiki?

### ISSUE THREAD

**Issue by zblace** [lingua-libre/BlueLL#14]
it seems that the $wgUser and body tags needs to be updated.

**Comment by Poslovitch** [comment]
For now, Lingua Libre is on MW 1.35 and is planned to move onto MW 1.39 in the coming year. The theme will be updated at that point :wink:

**Comment by zblace** [comment]
Any idea when this could be approximately? Is it likely in January or much later?

**Comment by hugolpz** [comment]
@zblace : Maybe this Autumn 2023, maybe later. We are an open source, volunteers-lead project so we lack steam. If your team has the required skills to check if there is compatibility we welcome such contributions.

**Comment by jdlrobson** [comment]
The above patch should take care of this. There are breaking changes in 1.41 that will cause the skin to break altogether without any action. Let me know if you have any questions (and more context can be found at https://phabricator.wikimedia.org/T306942 if needed)

**Comment by jdlrobson** [comment]
Just following up here. The skin is broken again in 1.41. Let me know if you need help updating it. I've stopped featuring it on https://skins.wmcloud.org/ in the mean time since it is broken.

**Comment by hugolpz** [comment]
Hello @jdlrobson , thank you for the ping.
I believe we have no one active on this project at the moment.
We welcome PR for sure.
