### ISSUE TITLE
Is this skin maintained?

### ISSUE THREAD

**Issue by jdlrobson** [lingua-libre/BlueLL#4]
This skin has been marked as unmaintained on https://www.mediawiki.org/wiki/Skin:BlueLL

It would be great if this is not true. 

I've posted #3. If merged this would make this maintained again and we can update the associated MediaWiki page.

**Comment by hugolpz** [comment]
Hello @jdlrobson,
We have a gap of maintenance from October 2020 to March 2021.
I'am a simple coordinator with very limited code knowledge.
We closed a call for developers with various aspects including this skin in early January, and expect someone to take over the maintenance in March 2021.

Could I learn more about your knowledge of this repository ?

**Comment by jdlrobson** [comment]
I mostly focus on mediawiki support for skins. I just noticed while auditing skins listed on mediawiki.org this one will break in the upcoming release in 1.36 (which is sometime in the summer of this year). Great to hear someone will take over maintainance in March.

**Comment by hugolpz** [comment]
Wikimedia France Is hiring a freelance. This specific mediawiki upgrade have been mentioned as a cause of concern. They/We are on it. :+1:

**Comment by hugolpz** [comment]
@jdlrobson : the skin is now actively monitored and we are considering your pull request.

I think we will soon :
- Review your PR #3 
- Consider this skin as `maintained`
- Edit [skin page](https://www.mediawiki.org/wiki/Skin:BlueLL) accordingly
- Close this issue

**Comment by jdlrobson** [comment]
Marked as stable. Thanks!
