### ISSUE TITLE
Migrate accepted css from Mediawiki:Common.css to relevant css file(s)

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/BlueLL#5]
Current css tests:
- [MediaWiki:Common.css](https://lingualibre.org/wiki/MediaWiki:Common.css)

Change to review before integration :
- [x] CuztomSubtitle's z-index fix : https://github.com/lingua-libre/CustomSubtitle/issues/1
- [x] Redirect colors
- [x] Spacing fix

File to expand:
- [BlueLL/assets/stylesheets/main.css](https://github.com/lingua-libre/BlueLL/blob/master/assets/stylesheets/main.css)
- [BlueLL/assets/stylesheets/content.css](https://github.com/lingua-libre/BlueLL/blob/master/assets/stylesheets/content.css)

**Comment by hugolpz** [comment]
Close. Should be ok with 1.35.

**Comment by hugolpz** [comment]
(missread.)

**Comment by Poslovitch** [comment]
What's the "spacing fix" ?

**Comment by hugolpz** [comment]
Line spacing is or was occasionally weird.
