### ISSUE TITLE
Remove margin, padding

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/BlueLL#6]
This [2 css rules](https://github.com/lingua-libre/BlueLL/blob/5aa7c3022f32e7b1f4a30ad9632b1898d6745758/assets/stylesheets/main.css#L12-L16) are creating troubles.

Please inspect a discussion and disactivate them in the inspector to see implied effect.

@Seb35 (If in your scope).

**Comment by Poslovitch** [comment]
Since they got removed, i'm closing this issue. It's worth noting, however, that their removal also induced a bunch of other issues, which we'll be fixing down the line.

**Comment by hugolpz** [comment]
Yes. The top bar and footer should keep the `* { margin:0; padding:0; }` to restore the initial elegance. I havent fixed this yet.
