### ISSUE TITLE
Add BlueLL to translatewiki

### ISSUE THREAD

**Issue by amire80** [lingua-libre/BlueLL#8]
Hi!

We already support the RecordWizard extensions in translatewiki, but not the BlueLL skin, and we'd love to support it!

See the translatewiki task: https://phabricator.wikimedia.org/T283956

We identified three things to do for it:

1. Already done: Submit a change for translatewiki configuration. Patch at https://gerrit.wikimedia.org/r/c/translatewiki/+/697091/ .
2. Make all BlueLL messages keys unique and consistently prefixed (except the skin identifier message).
3. Give the @translatewiki GitHub account permissions to commit there. It's already given in RecordWizard. Explanation here: https://translatewiki.net/wiki/Setup_of_a_new_project#Access_for_delivering_translation_updates

I'll submit a patch for number 2, but I need your support with number 3.

Thanks! :)

**Comment by Poslovitch** [comment]
Seems like it's all working now. Thanks!
